name: Stale

on:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/stale@v10.0.0
        with:
          days-before-issue-stale: 14
          days-before-issue-close: 7
