name: Code Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "**/ci.yml"
      - "**/go.{mod,sum}"
      - "**.go"
      - go.work
      - go.work.sum

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  static-checks:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: ".go-version"
          cache: true
          cache-dependency-path: |
            go.work.sum
            **/go.sum

      - name: Verify go.mod is tidy
        run: |
          go mod tidy -go=$(cat .go-version)
          git diff --exit-code

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: v2.11.3
          args: --timeout=3m

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: ".go-version"
          cache: true
          cache-dependency-path: |
            go.work.sum
            **/go.sum

      - name: Run tests
        run: |
          go test -v ./.dagger/.
