name: Code Integration

on:
  push:
    paths:
      - "**/ci.yml"
      - "**/go.{mod,sum}"
      - "**.go"
      - go.work
      - go.work.sum
  pull_request:
    paths:
      - "**/ci.yml"
      - "**/go.{mod,sum}"
      - "**.go"
      - go.work
      - go.work.sum

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  static-checks:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: ".go-version"
          cache: true
          cache-dependency-path: |
            go.work.sum
            **/go.sum

      - name: Verify go.mod is tidy
        run: |
          cd .dagger || exit 1
          go mod tidy -go=$(cat ../.go-version)
          git diff --exit-code go.mod

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: v2.11.3
          args: --timeout=3m ./.dagger/.

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: ".go-version"
          cache: true
          cache-dependency-path: |
            go.work.sum
            **/go.sum

      - name: Run tests
        run: |
          go test -v ./.dagger/.
