name: Cleanup ghcr.io nightly images

on:
  schedule:
    - cron: "25 6 * * *" # Daily nightly build at 6:25 AM UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Keep last 7 nightly builds
        uses: dataaxiom/ghcr-cleanup-action@244b3e8a35c266981a44b7e35da0c0e6a29b48a0
        with:
          token: ${{ secrets.GHCR_TOKEN }}
          delete-tags: nightly-*
          older-than: 7 days
          delete-untagged: true
