name: Cleanup Untagged GHCR Images

on:
  schedule:
    - cron: "0 4 */15 * *" # 4 AM, every 15 days
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-slim
    permissions:
      packages: write

    steps:
      - name: Delete untagged images
        uses: dataaxiom/ghcr-cleanup-action@244b3e8a35c266981a44b7e35da0c0e6a29b48a0
        with:
          delete-untagged: true
          delete-ghost-images: true
